#Pandas Series

##Pandas Series and DataFrames

###1. What is a Series?

A Pandas Series is like a column in a table.
It is a one-dimensional array that can hold data of any type (integers, strings, floats, etc.).

In [4]:
import pandas as pd

# Create a list
a = [1, 7, 2]

# Convert list to Pandas Series
myvar = pd.Series(a)

print(myvar)

0    1
1    7
2    2
dtype: int64

###Access a Value by Index

In [5]:
print(myvar[0])  # Output: 1

1

###Create Your Own Labels

You can assign custom labels using the index argument.

In [6]:
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a, index=["x", "y", "z"])

print(myvar)

x    1
y    7
z    2
dtype: int64

###Access a Value by Label:

In [7]:
print(myvar["y"])  # Output: 7

7

##2. Series from Key/Value Objects (Dictionary)

You can also create a Series from a dictionary. The keys become the labels, and the values become the data.

In [8]:
import pandas as pd

calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories)

print(myvar)

day1    420
day2    380
day3    390
dtype: int64

###Select Specific Items Using Index

In [9]:
myvar = pd.Series(calories, index=["day1", "day2"])
print(myvar)

day1    420
day2    380
dtype: int64

##3. DataFrames

A DataFrame is a multi-dimensional table.
Think of it as a collection of Series (columns).

Example: Creating a DataFrame from a Dictionary

In [10]:
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

myvar = pd.DataFrame(data)

print(myvar)

   calories  duration
0       420        50
1       380        40
2       390        45