#Pandas: Reading Data and Analyzing DataFrames
##1. Reading CSV and JSON Files
###1.1 Read CSV Files

In [ ]:
import pandas as pd

# Load CSV file into a DataFrame
df_csv = pd.read_csv('data.csv')

# Print entire DataFrame
print(df_csv.to_string())

###1.2 Read JSON Files

In [ ]:
# Load JSON file into a DataFrame
df_json = pd.read_json('data.json')

print(df_json.to_string())

##2. Viewing the Data
###2.1 Using head()

The head() method returns the top rows of the DataFrame.
By default, it returns 5 rows, but you can specify a number:

In [ ]:
# First 10 rows
print(df_csv.head(10))

# First 5 rows (default)
print(df_csv.head())

###2.2 Using tail()

The tail() method returns the last rows of the DataFrame:

In [ ]:
# Last 5 rows
print(df_csv.tail())

##3. Get Info About the Data

The info() method provides a summary of the DataFrame:

In [ ]:
print(df_csv.info())

Example Output:

In [ ]:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  169 non-null    int64
 1   Pulse     169 non-null    int64
 2   Maxpulse  169 non-null    int64
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB

##4. Handling Null Values

Empty or null values can affect data analysis. You may want to clean your data before analysis.

In [ ]:
# Remove rows with any null values
df_clean = df_csv.dropna()

# Or fill null values with 0
df_filled = df_csv.fillna(0)